project:
  type: website
  output-dir: docs 

website:
  title: "Kennedy Spann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
        menu:
          - text: Homework 1
            href: projects/hw1/index.qmd
          - text: Homework 2
            href: projects/hw2/index.qmd
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



