project:
  type: website
  output-dir: docs 

website:
  title: "Kennedy Spann"
  navbar:
    left:
      - text: Home
        href: home.qmd
      - text: Resume
        href: resume.qmd
      - text: Homeworks
        menu:
          - text: Homework 1
            href: projects/hw1/hw1_questions.qmd
          - text: Homework 2
            href: projects/hw2/hw2_questions.qmd
      - text: Publications
        href: publications.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

