project:
  type: website
  output-dir: docs 

website:
  title: "Kennedy Spann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



