<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kennedy Spann">
<meta name="dcterms.date" content="2025-06-11">

<title>Poisson Regression Examples – Kennedy Spann</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6f31c532a3f1db322c3cd5af964b0560.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Kennedy Spann</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../home.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-homeworks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Homeworks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-homeworks">    
        <li>
    <a class="dropdown-item" href="../../projects/hw1/hw1_questions.html">
 <span class="dropdown-text">Homework 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/hw2/hw2_questions.html">
 <span class="dropdown-text">Homework 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/hw3/hw3_questions.html">
 <span class="dropdown-text">Homework 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/hw4/hw4_updated.html">
 <span class="dropdown-text">Homework 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#blueprinty-case-study" id="toc-blueprinty-case-study" class="nav-link active" data-scroll-target="#blueprinty-case-study">Blueprinty Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#estimation-of-simple-poisson-model" id="toc-estimation-of-simple-poisson-model" class="nav-link" data-scroll-target="#estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</a></li>
  </ul></li>
  <li><a href="#deriving-the-mle-for-the-poisson-distribution" id="toc-deriving-the-mle-for-the-poisson-distribution" class="nav-link" data-scroll-target="#deriving-the-mle-for-the-poisson-distribution">Deriving the MLE for the Poisson Distribution</a>
  <ul class="collapse">
  <li><a href="#estimation-of-poisson-regression-model" id="toc-estimation-of-poisson-regression-model" class="nav-link" data-scroll-target="#estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</a></li>
  </ul></li>
  <li><a href="#airbnb-case-study" id="toc-airbnb-case-study" class="nav-link" data-scroll-target="#airbnb-case-study">AirBnB Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#poisson-regression-model-number-of-bookings-by-reviews" id="toc-poisson-regression-model-number-of-bookings-by-reviews" class="nav-link" data-scroll-target="#poisson-regression-model-number-of-bookings-by-reviews">Poisson Regression Model: Number of Bookings by Reviews</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kennedy Spann </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 11, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. Unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p><em>Number of Patents by Customer Status</em></p>
<div id="0c4c6f45" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-3-output-1.png" width="816" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.</p>
<p><em>Compare regions and ages by customer status</em></p>
<div id="2e52136d" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>region      Midwest  Northeast  Northwest  South  Southwest
iscustomer                                                 
0               187        273        158    156        245
1                37        328         29     35         52</code></pre>
</div>
</div>
<div id="785313ac" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>             count       mean       std   min   25%   50%    75%   max
iscustomer                                                            
0           1019.0  26.101570  6.945426   9.0  21.0  25.5  31.25  47.5
1            481.0  26.900208  7.814678  10.0  20.5  26.5  32.50  49.0</code></pre>
</div>
</div>
<div id="d063b3dd" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_48970/2292223956.py:7: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
</code></pre>
</div>
</div>
<div id="ca07ef27" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-8-output-1.png" width="1141" height="565" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From this histogram we can see higher level of customers in the Northeast region, age seems to be fairly constant between regions, and to confirm these inital assumptions a logistic regression was run:</p>
<div id="453e9584" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyrsm <span class="im">as</span> rsm</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run logistic regression</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>clf_1 <span class="op">=</span> rsm.model.logistic(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>blue,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    rvar<span class="op">=</span><span class="st">"iscustomer"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    lev<span class="op">=</span><span class="dv">1</span>,  <span class="co"># If iscustomer is numeric</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    evar<span class="op">=</span>[<span class="st">"age_group"</span>, <span class="st">"region"</span>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>clf_1.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic regression (GLM)
Data                 : Not provided
Response variable    : iscustomer
Level                : 1
Explanatory variables: age_group, region
Null hyp.: There is no effect of x on iscustomer
Alt. hyp.: There is an effect of x on iscustomer

                                               OR     OR%  coefficient  std.error  z.value p.value     
Intercept                                   0.222  -77.8%       -1.505      0.366   -4.106  &lt; .001  ***
age_group[Interval(15, 20, closed='left')]  0.865  -13.5%       -0.145      0.354   -0.411   0.681     
age_group[Interval(20, 25, closed='left')]  0.667  -33.3%       -0.405      0.345   -1.175    0.24     
age_group[Interval(25, 30, closed='left')]  0.759  -24.1%       -0.275      0.345   -0.798   0.425     
age_group[Interval(30, 35, closed='left')]  0.781  -21.9%       -0.247      0.351   -0.704   0.482     
age_group[Interval(35, 40, closed='left')]  1.172   17.2%        0.159      0.370    0.428   0.668     
age_group[Interval(40, 45, closed='left')]  2.252  125.2%        0.812      0.448    1.813    0.07    .
age_group[Interval(45, 50, closed='left')]  6.455  545.5%        1.865      0.971    1.921   0.055    .
region[Northeast]                           6.648  564.8%        1.894      0.202    9.371  &lt; .001  ***
region[Northwest]                           0.976   -2.4%       -0.024      0.274   -0.087   0.931     
region[South]                               1.126   12.6%        0.118      0.264    0.449   0.654     
region[Southwest]                           1.143   14.3%        0.134      0.239    0.560   0.576     

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Pseudo R-squared (McFadden): 0.136
Pseudo R-squared (McFadden adjusted): 0.124
Area under the RO Curve (AUC): 0.735
Log-likelihood: -812.401, AIC: 1648.802, BIC: 1712.545
Chi-squared: 255.763, df(11), p.value &lt; 0.001 
Nr obs: 1,498 (2 obs. dropped)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/conda/lib/python3.12/site-packages/xgboost/core.py:377: FutureWarning:

Your system has an old version of glibc (&lt; 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc &gt;= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
</code></pre>
</div>
</div>
<p>Results show…</p>
<ul>
<li><strong>Region</strong> is a stronger predictor than age when it comes to customer likelihood.
<ul>
<li>📍 <strong>Northeast</strong> region stands out:
<ul>
<li>Individuals in the Northeast are 6.6× more likely to be customers than those in the Midwest (statistically significant, p &lt; 0.001).</li>
</ul></li>
<li>Older age group (45–50) shows higher odds of being customers (OR ≈ 6.5), but result is marginally significant (p ≈ 0.055). Also, less data on this age group.</li>
</ul></li>
</ul>
</section>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.</p>
<p><em>Mathematically the likelihood for</em> <span class="math inline">\(Y \sim \text{Poisson}(\lambda)\)</span>. Note that <span class="math inline">\(f(Y|\lambda) = e^{-\lambda}\lambda^Y/Y!\)</span>.</p>
<p><span class="math display">\[
L(\lambda \mid Y_1, \ldots, Y_n) = \prod_{i=1}^n f(Y_i \mid \lambda)
= \prod_{i=1}^n \frac{e^{-\lambda} \lambda^{Y_i}}{Y_i!}
\]</span></p>
<p><span class="math display">\[
L(\lambda \mid \mathbf{Y}) = e^{-n\lambda} \lambda^{\sum_{i=1}^n Y_i} \prod_{i=1}^n \frac{1}{Y_i!}
\]</span></p>
<p><span class="math display">\[
\log L(\lambda \mid \mathbf{Y}) = -n\lambda + \left( \sum_{i=1}^n Y_i \right) \log \lambda - \sum_{i=1}^n \log(Y_i!)
\]</span></p>
<p><em>Plot of lambda on the horizontal axis and the likelihood (or log-likelihood) on the vertical axis for a range of lambdas (use the observed number of patents as the input for Y).</em></p>
<div id="63adf759" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-11-output-1.png" width="845" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="deriving-the-mle-for-the-poisson-distribution" class="level2">
<h2 class="anchored" data-anchor-id="deriving-the-mle-for-the-poisson-distribution">Deriving the MLE for the Poisson Distribution</h2>
<p>We start with the log-likelihood function:</p>
<p><span class="math display">\[
\log L(\lambda) = \left( \sum_{i=1}^n Y_i \right) \log \lambda - n\lambda + \text{constant}
\]</span></p>
<p>Taking the derivative with respect to <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
\frac{d}{d\lambda} \log L(\lambda) = \frac{\sum Y_i}{\lambda} - n
\]</span></p>
<p>Setting this equal to zero and solving for <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
\frac{\sum Y_i}{\lambda} = n \quad \Rightarrow \quad \lambda = \frac{\sum Y_i}{n} = \bar{Y}
\]</span></p>
<p>Thus, the maximum likelihood estimate is:</p>
<p><span class="math display">\[
\lambda_{\text{MLE}} = \bar{Y}
\]</span></p>
<p><strong>Lamda MLE from optimization: 3.6847</strong></p>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
<p><em>Below is an <strong>updated likelihood or log-likelihood function</strong> with an additional argument to take in a covariate matrix X. Also the parameter of the model has changed from lambda to the beta vector. In this model, lambda must be a positive number, so we choose the inverse link function g_inv() to be exp() so that</em> <span class="math inline">\(\lambda_i = e^{X_i'\beta}\)</span>.</p>
<div id="ff8b782d" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>             Coefficient  Std. Error
Intercept         1.3447      0.0423
Age (std)        -0.0577      0.0149
Age^2 (std)      -0.1558      0.0195
Northeast         0.0292      0.0557
Northwest        -0.0176      0.0644
South             0.0566      0.0839
Southwest         0.0506      0.0566
Customer          0.2076      0.0061</code></pre>
</div>
</div>
<p><em>Checked results using Python sm.GLM() function.</em></p>
<div id="c16e9a9a" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                patents   No. Observations:                 1500
Model:                            GLM   Df Residuals:                     1492
Model Family:                 Poisson   Df Model:                            7
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -3258.1
Date:                Wed, 11 Jun 2025   Deviance:                       2143.3
Time:                        11:17:35   Pearson chi2:                 2.07e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.1360
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          z      P&gt;|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const           1.3447      0.038     35.059      0.000       1.270       1.420
age_std        -0.0577      0.015     -3.843      0.000      -0.087      -0.028
age_squared    -0.1558      0.014    -11.513      0.000      -0.182      -0.129
Northeast       0.0292      0.044      0.669      0.504      -0.056       0.115
Northwest      -0.0176      0.054     -0.327      0.744      -0.123       0.088
South           0.0566      0.053      1.074      0.283      -0.047       0.160
Southwest       0.0506      0.047      1.072      0.284      -0.042       0.143
iscustomer      0.2076      0.031      6.719      0.000       0.147       0.268
===============================================================================</code></pre>
</div>
</div>
<section id="results" class="level4">
<h4 class="anchored" data-anchor-id="results">Results</h4>
<p><em>Each coefficient represents the log-change in the expected count per unit change in that variable.</em></p>
<p><strong>🔹 Intercept = 1.3447</strong> → When all variables are 0 (e.g., average age, non-customer, reference region), expected log-patents ≈ 1.34 → patents ≈ exp(1.3447) ≈ 3.84</p>
<p><strong>🔹 Customer = 0.2076</strong> → Being a customer is associated with a +0.2076 increase in log-patents → That’s about 23% more patents</p>
<p><strong>🔹 Age (std) = -0.0577, Age² (std) = -0.1558</strong> → Slight negative linear and stronger negative quadratic effect of age → Implies patents peak at middle age and drop off for older firms</p>
<p><strong>🔹 Regions: all relatively small effects; not statistically strong without p-values, but hint at mild differences</strong></p>
<p><em>So what is the conslusion of the effect of Blueprinty’s software on patent success?</em></p>
<ul>
<li>Created two fake datasets: X_0 and X_1 where X_0 is the X data but with iscustomer=0 for every observation and X_1 is the X data but with iscustomer=1 for every observation. Then, used X_0 and your fitted model to get the vector of predicted number of patents (y_pred_0) for every firm in the dataset, and use X_1 to get Y_pred_1 for every firm. Then subtracted y_pred_1 minus y_pred_0 and take the average of that vector of differences.</li>
</ul>
<div id="867ff1e0" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the fitted GLM model (assuming you've already run the sm.GLM Poisson model above)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Model: poisson_results</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Design matrix: X_df</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create X_0 and X_1</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>X_0 <span class="op">=</span> X_df.copy()</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>X_0[<span class="st">'iscustomer'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>X_1 <span class="op">=</span> X_df.copy()</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>X_1[<span class="st">'iscustomer'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict patent counts under both scenarios</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>y_pred_0 <span class="op">=</span> poisson_results.predict(X_0)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>y_pred_1 <span class="op">=</span> poisson_results.predict(X_1)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average treatment effect</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> y_pred_1 <span class="op">-</span> y_pred_0</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>average_effect <span class="op">=</span> np.mean(delta)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated average increase in patents per firm due to Blueprinty's software: </span><span class="sc">{</span>average_effect<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated average increase in patents per firm due to Blueprinty's software: 0.7928</code></pre>
</div>
</div>
<div id="7807eae1" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-17-output-1.png" width="661" height="468" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City. The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
</section>
<section id="poisson-regression-model-number-of-bookings-by-reviews" class="level3">
<h3 class="anchored" data-anchor-id="poisson-regression-model-number-of-bookings-by-reviews">Poisson Regression Model: Number of Bookings by Reviews</h3>
<div id="0ef5acac" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:      number_of_reviews   No. Observations:                30160
Model:                            GLM   Df Residuals:                    30149
Model Family:                 Poisson   Df Model:                           10
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -5.2418e+05
Date:                Wed, 11 Jun 2025   Deviance:                   9.2689e+05
Time:                        11:17:35   Pearson chi2:                 1.37e+06
No. Iterations:                    10   Pseudo R-squ. (CS):             0.6840
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          z      P&gt;|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         3.4980      0.016    217.396      0.000       3.467       3.530
days                       5.072e-05   3.91e-07    129.755      0.000       5e-05    5.15e-05
bathrooms                    -0.1177      0.004    -31.394      0.000      -0.125      -0.110
bedrooms                      0.0741      0.002     37.197      0.000       0.070       0.078
price                     -1.791e-05   8.33e-06     -2.151      0.031   -3.42e-05   -1.59e-06
review_scores_cleanliness     0.1131      0.001     75.611      0.000       0.110       0.116
review_scores_location       -0.0769      0.002    -47.796      0.000      -0.080      -0.074
review_scores_value          -0.0911      0.002    -50.490      0.000      -0.095      -0.088
room_type_Private room       -0.0105      0.003     -3.847      0.000      -0.016      -0.005
room_type_Shared room        -0.2463      0.009    -28.578      0.000      -0.263      -0.229
instant_bookable_t            0.3459      0.003    119.666      0.000       0.340       0.352
=============================================================================================</code></pre>
</div>
</div>
<section id="interpretation-of-poisson-regression-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-poisson-regression-coefficients">Interpretation of Poisson Regression Coefficients</h4>
<p>In a Poisson regression with a log-link, coefficients represent log-changes in expected number of reviews.<br>
To interpret them as <strong>percent changes</strong>, we use the formula:</p>
<p><span class="math display">\[
\text{Percent Change} = \left( \exp(\beta) - 1 \right) \times 100
\]</span></p>
<hr>
<section id="effect-of-listing-features-on-number-of-reviews" class="level5">
<h5 class="anchored" data-anchor-id="effect-of-listing-features-on-number-of-reviews">📊 Effect of Listing Features on Number of Reviews</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 33%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Coefficient (β)</th>
<th style="text-align: right;">% Change in Expected Reviews</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>instant_bookable_t</code></td>
<td style="text-align: right;">0.346</td>
<td style="text-align: right;"><strong>+41%</strong></td>
<td>Instantly bookable listings get ~41% more reviews</td>
</tr>
<tr class="even">
<td><code>room_type_Private room</code></td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;"><strong>-1%</strong></td>
<td>Slightly fewer reviews vs.&nbsp;entire home</td>
</tr>
<tr class="odd">
<td><code>room_type_Shared room</code></td>
<td style="text-align: right;">-0.246</td>
<td style="text-align: right;"><strong>-22%</strong></td>
<td>Shared rooms get ~22% fewer reviews</td>
</tr>
<tr class="even">
<td><code>bedrooms</code></td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;"><strong>+7.7%</strong></td>
<td>Each additional bedroom → ~8% more reviews</td>
</tr>
<tr class="odd">
<td><code>bathrooms</code></td>
<td style="text-align: right;">-0.118</td>
<td style="text-align: right;"><strong>-11%</strong></td>
<td>Each additional bathroom → ~11% fewer reviews</td>
</tr>
<tr class="even">
<td><code>price</code></td>
<td style="text-align: right;">-0.000018</td>
<td style="text-align: right;">~0%</td>
<td>Slightly fewer reviews for higher prices</td>
</tr>
<tr class="odd">
<td><code>review_scores_cleanliness</code></td>
<td style="text-align: right;">0.113</td>
<td style="text-align: right;"><strong>+12%</strong></td>
<td>Higher cleanliness = more reviews</td>
</tr>
<tr class="even">
<td><code>review_scores_location</code></td>
<td style="text-align: right;">-0.077</td>
<td style="text-align: right;"><strong>-7.4%</strong></td>
<td>Surprisingly, higher location scores → fewer reviews</td>
</tr>
<tr class="odd">
<td><code>review_scores_value</code></td>
<td style="text-align: right;">-0.091</td>
<td style="text-align: right;"><strong>-8.7%</strong></td>
<td>Higher value score = fewer reviews</td>
</tr>
<tr class="even">
<td><code>days</code></td>
<td style="text-align: right;">0.0000507</td>
<td style="text-align: right;">~+0.005% per day</td>
<td>Older listings have more reviews</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">🧠 Summary</h4>
<ul>
<li>The <strong>largest positive effects</strong> come from <code>instant_bookable</code>, <code>cleanliness</code>, and <code>bedrooms</code>.</li>
<li><strong>Shared rooms underperform</strong> significantly compared to entire homes.</li>
<li><strong>Review score for value and location</strong> surprisingly have small <strong>negative</strong> effects, possibly due to multicollinearity or confounding with price.</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>